# Generated by Django 3.1.3 on 2020-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(default='9820071118', max_length=12),
            preserve_default=False,
        ),
    ]
